name: finbud_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  font_awesome_flutter: ^10.7.0

  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  intl: ^0.18.0
  calendar_agenda:
    path: dev_lib/calendar_agenda
  carousel_slider: ^4.2.1
  card_swiper:
    path: dev_lib/card_swiper

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/img/
    - assets/img/finbud_logo.png

fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/font/Inter-Bold.ttf
          weight: 700


